package errors

import "errors"

var (
	ErrGithubUserNotFound               = errors.New("github user with provided username not found")
	ErrInvalidToken                     = errors.New("invalid token")
	ErrAccessDenied                     = errors.New("access denied")
	ErrAccessDeniedAnotherUser          = errors.New("access denied - another user")
	ErrUserNotFound                     = errors.New("user not found")
	ErrProjectNotFound                  = errors.New("project not found")
	ErrEmailAlreadyExists               = errors.New("email already exists")
	ErrUsernameAlreadyExists            = errors.New("username already exists")
	ErrGithubUsernameAlreadyExists      = errors.New("github username already exists")
	ErrInvalidUserRole                  = errors.New("invalid user role")
	ErrProjectNameAlreadyExists         = errors.New("project name already exists")
	ErrInvalidProjectName               = errors.New("invalid project name")
	ErrProjectActiveToIsInvalid         = errors.New("project date is not valid")
	ErrTaskNameIsInvalid                = errors.New("task name is not valid")
	ErrTaskCreatorUserIDNotFound        = errors.New("task creator id not found")
	ErrTaskNotFound                     = errors.New("task not found")
	ErrParticipantNotFound              = errors.New("participant not found")
	ErrParticipantsNotFound             = errors.New("participants not found")
	ErrTaskParticipantIDNotFound        = errors.New("task participant id not found")
	ErrInvalidStatus                    = errors.New("invalid status")
	ErrInvalidProjectID                 = errors.New("invalid project id")
	ErrTaskSuggestedEstimateIsInvalid   = errors.New("task suggested estimate is not valid")
	ErrInvalidParticipantRole           = errors.New("invalid participant role")
	ErrInvalidUserID                    = errors.New("invalid user id")
	ErrAccessDeniedWrongParticipantRole = errors.New("access denied - wrong participant role")
	ErrParticipantAlreadyExists         = errors.New("participant already exists")
	ErrTaskIDIsInvalid                  = errors.New("task id is not valid")
	ErrTokenHeaderIsEmpty               = errors.New("token header is empty")
	ErrTaskRealEstimateIsInvalid        = errors.New("task real estimate is not valid")
	ErrUsersNotFound                    = errors.New("users not found")
	ErrEmptyUsernameOrPassword          = errors.New("username or password is empty")
	ErrUserIsNotOnProject               = errors.New("user is not on project")
	ErrInvalidActiveTo                  = errors.New("invalid active_to date")
	ErrTeamLeadAlreadyExists            = errors.New("team lead already exists")
	ErrRepositoryURLIsEmpty             = errors.New("repository url is empty")
	ErrRepositoryURLWrongFormat         = errors.New("repository url has wrong format")
)
