CREATE TYPE role AS ENUM ('student', 'project_manager', 'admin');
CREATE TYPE role_participant AS ENUM ('owner', 'team_lead', 'participant');

CREATE TYPE status AS ENUM ('TODO', 'In progress', 'In review', 'Testing', 'Done');

CREATE TABLE users
(
    id              uuid PRIMARY KEY NOT NULL,
    role            role                      DEFAULT 'student',
    color_code      VARCHAR          NOT NULL DEFAULT '#FFFFFF',
    email           VARCHAR UNIQUE   NOT NULL,
    username        VARCHAR UNIQUE   NOT NULL,
    first_name      VARCHAR          NOT NULL,
    last_name       VARCHAR          NOT NULL,
    "group"         VARCHAR          NOT NULL,
    github_username VARCHAR UNIQUE   NOT NULL,
    hashed_password VARCHAR          NOT NULL
);

CREATE TABLE projects
(
    id          bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR NOT NULL,
    description TEXT,
    photo_url   VARCHAR,
    report_url  VARCHAR,
    report_name VARCHAR,
    repo_url    VARCHAR,
    active_to   DATE
);

CREATE TABLE participants
(
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    role       role_participant DEFAULT 'participant',
    user_id    uuid REFERENCES users (id) ON DELETE CASCADE,
    project_id BIGINT REFERENCES projects (id) ON DELETE CASCADE
);

CREATE TABLE tasks
(
    id                 BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name               VARCHAR   NOT NULL,
    description        TEXT,
    suggested_estimate INT,
    real_estimate      INT,
    participant_id     BIGINT REFERENCES participants (id) ON DELETE CASCADE,
    creator_id         BIGINT REFERENCES participants (id) ON DELETE CASCADE,
    status             status    NOT NULL DEFAULT 'TODO',
    created_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    project_id         BIGINT REFERENCES projects (id) ON DELETE CASCADE
);
