CREATE TABLE users
(
    id              bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    role            smallint                DEFAULT 0,
    color_code      VARCHAR        NOT NULL DEFAULT '#FFFFF',
    email           VARCHAR UNIQUE NOT NULL,
    username        VARCHAR UNIQUE NOT NULL,
    first_name      VARCHAR        NOT NULL,
    last_name       VARCHAR        NOT NULL,
    "group"         VARCHAR        NOT NULL,
    github_username VARCHAR UNIQUE NOT NULL,
    hashed_password VARCHAR        NOT NULL
);

CREATE TABLE projects
(
    id          bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR NOT NULL,
    description TEXT,
    photo_url   VARCHAR,
    report_url  VARCHAR,
    report_name VARCHAR,
    repo_url    VARCHAR,
    active_to   DATE
);

CREATE TABLE participants
(
    id         bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    role       smallint DEFAULT 0,
    user_id    bigint REFERENCES users (id) ON DELETE CASCADE,
    project_id bigint REFERENCES projects (id) ON DELETE CASCADE
);